title: GNNs â™¥ Urban Form
logo: images/leicester-1864_emb_gnnuf_model_v0-5_map-bivariate.png
description: Stefano De Sabbata, Andrea Ballatore, Pengyuan Liu and Nicholas J. Tate
show_downloads: true
theme: jekyll-theme-minimal
plugins:
  - jemoji